---
title: "Three Species Model of Zika Virus"
author: "Courtney D. Shelley"
date: "March 21, 2016"
header-includes:
   - \usepackage{mathrsfs}
   - \usepackage{amsmath}
output: pdf_document
---

```{r fig.width=4, fig.height=2.5,echo=FALSE, fig.align='center'}
setwd("~/Dropbox/BarkerLab/ZIKV")
library(png)
library(grid)
img <- readPNG("ZikaModel1.png")
 grid.raster(img)
```


##Host ODEs

$\frac{dS_H}{dt} = b_H(N_H-I_H) - \beta_{V1H} \frac{S_H}{N_H}I_{V1} - \beta_{V2H} I_{V2}-\beta_{HH}\frac{S_H I_H}{N_H^2} - d_H S_H$

$\frac{dE_H}{dt} = \left( \beta_{V1H}I_{V1} + \beta_{V2H}I_{V2} + \beta_{HH}\frac{I_H}{N_H} \right) \frac{S_H}{N_H} - \epsilon_H E_H - d_H E_H$

$\frac{dI_H}{dt} = b_H I_H + \epsilon_H E_H - \gamma_H I_H - d_H I_H$

$\frac{dR_H}{dt} = \gamma_H I_H - d_H R_H$

>$\Longrightarrow \frac{dN_H}{dt} = b_H N_H - d_H N_H = (b_H - d_H)N_H$

##Vector 1 ODEs

$\frac{dS_{V1}}{dt} = \theta_{V1}P_{V1} - \beta_{HV1}S_{V1}\frac{I_H}{N_H} - d_{V1}S_{V1}\frac{N_{V1}}{K_{V1}}$

$\frac{dE_{V1}}{dt} = \beta_{HV1}S_{V1}\frac{I_H}{N_H}-\epsilon_{V1}E_{V1}-d_{V1}E_{V1}\frac{N_{V1}}{K_{V1}}$

$\frac{dI_{V1}}{dt} = \epsilon_{V1}E_{V1} - d_{V1}I_{V1}\frac{N_{V1}}{K_{V1}}$

>$\Longrightarrow \frac{dN_{V1}}{dt} = \theta_{V1}P_{V1} - d_{V1}N_{V1}\frac{N_{V1}}{K_{V1}}$

##Vector 2 ODEs

$\frac{dS_{V2}}{dt} = \theta_{V2}P_{V2} - \beta_{HV2}S_{V2}\frac{I_H}{N_H} - d_{V2}S_{V2}\frac{N_{V2}}{K_{V2}}$

$\frac{dE_{V2}}{dt} = \beta_{HV2}S_{V2}\frac{I_H}{N_H} - \epsilon_{V2}E_{V2} - d_{V2}E_{V2}\frac{N_{V2}}{K_{V2}}$

>$\Longrightarrow \frac{dN_{V2}}{dt} = \theta_{V2}P_{V2} - d_{V2}N_{V2}\frac{N_{V2}}{K_{V2}}$


Per van den Driessche (2001), we focus our attention only on pools with incoming new infections. For vertical transmission, this is only found in the host species:

>$\frac{dE_H}{dt} = \left( \beta_{V1H}I_{V1} + \beta_{V2H}I_{V2} + \beta_{HH}\frac{I_H}{N_H}  \right) \frac{S_H}{N_H} - \epsilon_H E_H - d_H E_H$

>>$= \mathscr{F}_V - \mathscr{V}_V = \left( \beta_{HH} \frac{I_H S_H}{N_H^2} \right) - \left( \epsilon_{H}E_H + d_H E_H - \left(\beta_{V1H}I_{V1} + \beta_{V2H}I_{V2} + \beta_{HH}\frac{I_H}{N_H} \right) \right)$

>$\frac{dI_H}{dt} = b_H I_H + \epsilon_H E_H - \gamma_H I_H - d_H I_H$

>>$= \mathscr{F}_V - \mathscr{V}_V = \left( b_H I_H \right) - \left( \gamma_H I_H +d_H I_H - \epsilon_H E_H \right)$

Converting to matrix notation, 

\[
\mathscr{F}_V = 
\begin{bmatrix}
\beta_{HH}\frac{I_H S_H}{N_H^2}\\
b_H I_H
\end{bmatrix}
\text{, }
\mathscr{V}_V = 
\begin{bmatrix}
\epsilon_HE_H + d_HE_H - \left( \beta_{V1H}I_{V1} + \beta_{V2H}I_{V2} + \beta_{HH}\frac{I_H}{N_H}\right)\\
\gamma_H I_H + d_H I_H - \epsilon_H E_H.
\end{bmatrix}
\]

It follows that $F_V$ and $V_V$ are found as the Jacobian of $\mathscr{F}_V$ and $\mathscr{V}_V$:

\[
F_V = 
\begin{bmatrix}
0 & \beta_{HH}\frac{S_H}{N_H^2}\\
0 & b_H
\end{bmatrix}
\text{, and }
V_V = 
\begin{bmatrix}
\epsilon_H + dH & \frac{\beta_{HH}}{N_H}\\
-\epsilon_H & \gamma_H + d_H
\end{bmatrix}
\]

For the horizontal transmission component, focus is on pools with incoming new horizontally-acquired infection, 

\[
\frac{d}{dt}
\begin{bmatrix}
E_H\\
I_H\\
E_{V1}\\
I_{V1}\\
E_{V2}\\
I_{V2}
\end{bmatrix}
= \mathscr{F}_H - \mathscr{V}_H =
\begin{bmatrix}
\left( \beta_{V1H}I_{V1} + \beta_{V2H}I_{V2} + \beta_{HH}\frac{I_H}{N_H}\right)\frac{S_H}{N_H}\\
0\\
\beta_{HV1}S_{V1}\frac{I_H}{N_H}\\
0\\
\beta_{HV2}S_{V2}\frac{I_H}{N_H}\\
0
\end{bmatrix}
\text{ - }
\begin{bmatrix}
\epsilon_H E_H + d_H E_H\\
\gamma_H I_H + d_H I_H - \epsilon_H E_H - b_H I_H\\
\epsilon_{V1} E_{V1} + d_{V1}E_{V1}\frac{N_{V1}}{K_{V1}}\\
d_{V1}I_{V1}\frac{N_{V1}}{K_{V1}} - \epsilon_{V1}E_{V1}\\
\epsilon_{V2}E_{V2}+d_{V2}E_{V2}\frac{N_{V2}}{K_{V2}}\\
d_{V2}I_{V2}\frac{N_{V2}}{K_{V2}}-\epsilon_{V2}E_{V2}
\end{bmatrix}.
\]

$F_H$ and $V_H$ are again the Jacobian of $\mathscr{F}_H$ and $\mathscr{V}_H$. Thus, 

\[
F_H = 
\begin{bmatrix}
0 & \beta_{HH}\frac{S_H}{N_H^2} & 0 & \beta_{V1H}\frac{S_H}{N_H} & 0 & \beta_{V2H}\frac{S_H}{N_H}\\
0 & 0 & 0 & 0 & 0 & 0\\
0 & \beta_{HV1}\frac{S_{V1}}{N_H} & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0\\
0 & \beta_{HV2}\frac{S_{V2}}{N_H} & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0
\end{bmatrix}
\]

\[
V_H = 
\begin{bmatrix}
\epsilon_H + d_H & 0 & 0 & 0 & 0 & 0\\
-\epsilon_H & \gamma_H + d_H - b_H & 0 & 0 & 0 & 0\\
0 & 0 & \epsilon_{V1} + d_{V1}\kappa 1 & 0 & 0 & 0\\
0 & 0 & -\epsilon_{V1} & d_{V1}\kappa 1 & 0 & 0\\
0 & 0 & 0 & 0 & \epsilon_{V2} + d_{V2}\kappa 2 & 0\\
0 & 0 & 0 & 0 & -\epsilon_{V2} & d_{V2}\kappa 2 
\end{bmatrix}
\]

where $\kappa1 = \frac{N_{V1}}{K_{V1}}, \kappa2 = \frac{N_{V1}}{K_{V2}}.$

The reproductive number, $R_0$, equals the sum of the spectral radii of the next generation matrices, $F_V V_V^{-1} and F_H V_H^{-1}$.  That is, $R_0 = \rho(F_V V_V^{-1}) + \rho(F_H V_H^{-1}).$

For the vertical portion, 

\[
V_V^{-1} = \frac{-N_H}{\epsilon_H \beta_{HH} + N_H(\epsilon_H+d_H)(\gamma_H+d_H)}
\begin{bmatrix}
-(\gamma_H+d_H) & \frac{\beta_{HH}}{N_H}\\
-\epsilon_H & -(\epsilon_H+d_H)
\end{bmatrix}
\]

\[
F_V V_V^{-1} = \frac{1}{2}*\frac{N_H}{\epsilon_H\beta_{HH}+N_H(\epsilon_H+d_H)(\gamma_H+d_H)}
\begin{bmatrix}
\epsilon_H \beta_{HH}\frac{S_H}{N_H^2} & \beta_{HH}\frac{S_H}{N_H^2}(\epsilon_H+d_H)\\
\epsilon_H b_H & b_H(\epsilon_H + d_H)
\end{bmatrix}
\]

Letting A = $\frac{N_H}{\epsilon_H \beta_{HH}+N_H(\epsilon_H+d_H)(\gamma_H + d_H)}$, 

$\rho(F_V V_V^{-1}) = \frac{1}{2A}\left[\left(\frac{\epsilon_H\beta_{HH}S_H}{N_H^2} \right)^2- 2\left(\frac{\epsilon_H \beta_{HH}S_H b_H}{N_H^2} (\epsilon_H+d_H)\right)+4\left(\frac{\beta_{HH}S_H\epsilon_H b_H}{N_H^2}(\epsilon_H+d_H) \right)+ b_H^2(\epsilon_H+d_H)^2\right]^{-1/2}$

>>>$+\frac{1}{2A}\left[\frac{\epsilon_H\beta_{HH}S_H}{N_H^2} + b_H(\epsilon_H+d_H) \right]$

For the horizontal portion, 

\[
V_H^{-1} = 
\begin{bmatrix}
\frac{1}{\epsilon_H + d_H} & 0 & 0 & 0 & 0 & 0\\
\frac{\epsilon_H}{(\gamma_H + d_H - b_H)(\epsilon_H + d_H)} & \frac{1}{\gamma_H + d_H - b_H} & 0 & 0 & 0 & 0\\
0 & 0 & \frac{1}{\epsilon_{V1} + d_{V1}\kappa_1} & 0 & 0 & 0\\
0 & 0 & \frac{\epsilon_{V1}}{(\epsilon_{V1}+d_{V1}\kappa_1)(d_{V1}\kappa1)} & \frac{1}{d_{V1}\kappa_1} & 0 & 0\\
0 & 0 & 0 & 0 & \frac{1}{\epsilon_{V2}+d_{V2}\kappa_2} & 0\\
0 & 0 & 0 & 0 & \frac{\epsilon_{V2}}{(\epsilon_{V2}+d_{V2}\kappa_2)(d_{V2}\kappa_2)} & \frac{1}{d_{V2}\kappa_2}
\end{bmatrix}
\]

\[
F_H V_H^{-1} = 
\begin{bmatrix}
\frac{\beta_{HH}S_H\epsilon_H}{N_H^2 (\gamma_H+d_H-b_H)(\epsilon_H + d_H)} 
& \frac{\beta_{HH}S_H}{(\gamma_H+d_H-b_H)N_H^2} 
& \frac{\beta_{V1H} S_H \epsilon_{V1}}{N_H d_{V1}\kappa_1 (\epsilon_{V1}+d_{V1}\kappa_1)} 
& \frac{\beta_{V1H}S_H}{N_Hd_{V1}\kappa_1} 
& \frac{\epsilon_{V2}\beta_{V2H}S_H}{N_H d_{V2}\kappa_2 (\epsilon_{V2}+d_{V2}\kappa_2)} 
& \frac{\beta_{V2H}S_H}{N_H d_{V2}\kappa_2}\\
0 & 0 & 0 & 0 & 0 & 0\\
\frac{\beta_{HV1}S_{V1}\epsilon_H}{N_H (\gamma_H+d_H-b_H)(\epsilon_H + d_H)} 
& \frac{\beta_{HV1}S_{V1}}{N_H(\gamma_H+d_H-b_H)} & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0\\
\frac{\beta_{HV2}S_{V2}\epsilon_H}{N_H(\gamma_H+d_H-b_H)(\epsilon_H+d_H)} 
& \frac{\beta_{HV2}S_{V2}}{N_H(\gamma_H+d_H-b_H)} & 0 & 0 & 0 & 0\\
0 & 0 & 0 & 0 & 0 & 0
\end{bmatrix}
\]

Letting $A = \left(\frac{\beta_{HH S_H}}{N_H^2}\right)\left(\frac{\epsilon_H}{\gamma_H+d_H-b_H}\right)\left(\frac{1}{\epsilon_H+d_H}\right)$, C = $\left(\frac{\beta_{V1H}S_H}{N_H}\right)\left[\frac{\epsilon_{V1}}{(\epsilon_{V1}+d_{V1}\kappa_1)d_{V1}\kappa_1}\right]$, G = $\left(\frac{\beta_{HV1}S_{V1}}{N_H} \right) \left[\frac{\epsilon_H}{(\gamma_H + d_H - b_H)(\epsilon_H+d_H)}\right]$, E = $\frac{\epsilon_{V2}\beta_{V2H}S_H}{(\epsilon_{V2}+d_{V2}\kappa_2)d_{V2}\kappa_2N_H}$, and I = $\left(\frac{\beta_{HV2}S_{V2}}{N_H}\right)\left[\frac{\epsilon_H}{(\gamma_H+d_H-b_H)(\epsilon_H+d_H)}\right]$, 

>>>$\rho(F_H V_H^{-1}) = \frac{1}{2}(A + \sqrt(A^2 + 4CG + 4EI))$.